// Hand-authored pixel maps. Chars index per-sprite palettes; '.' transparent.
// Humanoids are 16x32, composed from a 20-row top and 12-row leg frames so
// every character shares consistent proportions. All face right; the sprite
// bank mirrors them for leftward travel.

import type { PixelMap, Palette } from '../../engine/sprites.ts'

const compose = (top: PixelMap, legs: PixelMap): PixelMap => [...top, ...legs]

// ---------------------------------------------------------------- Willy ---
const WILLY_TOP: PixelMap = [
  '......KKKKK.....',
  '......KKKKK.....',
  '......KKKKK.....',
  '......KKKKK.....',
  '.....RRRRRRR....',
  '....KKKKKKKKK...',
  '......SSSSS.....',
  '......SSSKS.....',
  '......SSSSS.....',
  '......SSSS......',
  '......WWWW......',
  '....UUWWWWUU....',
  '...UUUWWWWUUU...',
  '...UU.WWWW.UU...',
  '...SS.WWWW.SS...',
  '......UUUU......',
  '......UUUU......',
  '......TTTT......',
  '......TTTT......',
  '......TTTT......',
]
const LEGS_STAND: PixelMap = [
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....OO..OO.....',
  '....OOO..OOO....',
]
const LEGS_STRIDE: PixelMap = [
  '.....TT..TT.....',
  '....TT....TT....',
  '....TT....TT....',
  '...TT......TT...',
  '...TT......TT...',
  '..TT........TT..',
  '..TT........TT..',
  '..TT........TT..',
  '..TT........TT..',
  '..TT........TT..',
  '..OO........OO..',
  '.OOO........OOO.',
]
const LEGS_PASS: PixelMap = [
  '.....TT..TT.....',
  '.....TT..TT.....',
  '.....TT..TTT....',
  '.....TT...TT....',
  '.....TT..OOO....',
  '.....TT.........',
  '.....TT.........',
  '.....TT.........',
  '.....TT.........',
  '.....TT.........',
  '.....OO.........',
  '....OOO.........',
]

export const WILLY_PAL: Palette = {
  K: '#16161e', R: '#c0303a', S: '#e8b48a', W: '#f0f0e8',
  U: '#2a3a6a', T: '#1d2848', O: '#101018',
}
export const WILLY_FRAMES: PixelMap[] = [
  compose(WILLY_TOP, LEGS_STAND),
  compose(WILLY_TOP, LEGS_STRIDE),
  compose(WILLY_TOP, LEGS_PASS),
]

// ------------------------------------------------------- suit humanoids ---
const SUIT_TOP: PixelMap = [
  '................',
  '.....HHHHHH.....',
  '....HHHHHHHH....',
  '......SSSSS.....',
  '......SSSKS.....',
  '......SSSSS.....',
  '......SSSS......',
  '.....JJJJJJ.....',
  '....JJJJJJJJ....',
  '...JJ.JJJJ.JJ...',
  '...JJ.JJJJ.JJ...',
  '...SS.JJJJ.SS...',
  '......JJJJ......',
  '......JJJJ......',
  '......PPPP......',
  '......PPPP......',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
]
const SUIT_LEGS_A: PixelMap = [
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....PP..PP.....',
  '.....OO..OO.....',
  '....OOO..OOO....',
]
const SUIT_LEGS_B: PixelMap = [
  '.....PP..PP.....',
  '....PP....PP....',
  '....PP....PP....',
  '...PP......PP...',
  '...PP......PP...',
  '...PP......PP...',
  '..PP........PP..',
  '..PP........PP..',
  '..PP........PP..',
  '..PP........PP..',
  '..OO........OO..',
  '.OOO........OOO.',
]
export const SUIT_FRAMES: PixelMap[] = [
  compose(SUIT_TOP, SUIT_LEGS_A),
  compose(SUIT_TOP, SUIT_LEGS_B),
]

// ------------------------------------------------------ dress humanoids ---
const DRESS_TOP: PixelMap = [
  '................',
  '.....hhhhh......',
  '....hhhhhhh.....',
  '......SSSSS.....',
  '......SSSKS.....',
  '......SSSSS.....',
  '......SSSS......',
  '......DDDD......',
  '.....DDDDDD.....',
  '....DDDDDDDD....',
  '...DD.DDDD.DD...',
  '...SS.DDDD.SS...',
  '.....DDDDDD.....',
  '....DDDDDDDD....',
  '....DWWWWWWD....',
  '...DDWWWWWWDD...',
  '...DDWWWWWWDD...',
  '...DDWWWWWWDD...',
  '..DDDWWWWWWDDD..',
  '..DDDDDDDDDDDD..',
]
const DRESS_LEGS_A: PixelMap = [
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '.....OO..OO.....',
  '.....OO..OO.....',
]
const DRESS_LEGS_B: PixelMap = [
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '..DDDDDDDDDDDD..',
  '....OO....OO....',
  '....OO....OO....',
]
export const DRESS_FRAMES: PixelMap[] = [
  compose(DRESS_TOP, DRESS_LEGS_A),
  compose(DRESS_TOP, DRESS_LEGS_B),
]

// Per-type recolors of the shared humanoid bases.
export const HUMANOID_PALETTES: Record<string, Palette> = {
  butler: {
    H: '#202028', S: '#e0ae84', K: '#101014', J: '#26262e',
    P: '#1a1a22', O: '#0c0c10', W: '#e8e8e0',
  },
  chef: {
    H: '#f0f0ea', S: '#e0ae84', K: '#101014', J: '#e8e8e0',
    P: '#3a3a48', O: '#202028', W: '#e8e8e0',
  },
  gardener: {
    H: '#5a4a2a', S: '#d8a87a', K: '#101014', J: '#4a6a3a',
    P: '#6a5a3a', O: '#2e2418', W: '#e8e8e0',
  },
  sweep: {
    H: '#38302c', S: '#caa284', K: '#101014', J: '#48403a',
    P: '#38302c', O: '#181410', W: '#e8e8e0',
  },
  knight: {
    H: '#9aa4b8', S: '#9aa4b8', K: '#101014', J: '#7a86a0',
    P: '#5a6480', O: '#3a4258', W: '#e8e8e0',
  },
  maid: {
    h: '#7a4a28', S: '#e0ae84', K: '#101014', D: '#3a3a4a',
    O: '#1a1a22', W: '#f0f0ea',
  },
  maria: {
    h: '#8a8a92', S: '#e0ae84', K: '#101014', D: '#6a2a3a',
    O: '#1a1a22', W: '#f0f0ea',
  },
}

// ----------------------------------------------------------------- ghost ---
export const GHOST_FRAMES: PixelMap[] = [
  [
    '.....GGGGGG.....',
    '....GGGGGGGG....',
    '...GGGGGGGGGG...',
    '...GGKKGGKKGG...',
    '...GGKKGGKKGG...',
    '...GGGGGGGGGG...',
    '...GGGGKKGGGG...',
    '...GGGGGGGGGG...',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GG.GGGG.GGGG..',
    '..GG.GGGG.GG.G..',
    '..G..GG.G.GG....',
    '..G..GG.G.G.....',
    '.....G..G.......',
    '................',
  ],
  [
    '.....GGGGGG.....',
    '....GGGGGGGG....',
    '...GGGGGGGGGG...',
    '...GGKKGGKKGG...',
    '...GGKKGGKKGG...',
    '...GGGGGGGGGG...',
    '...GGGGKKGGGG...',
    '...GGGGGGGGGG...',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGGGGGGGGGG..',
    '..GGGG.GGGG.GG..',
    '..G.GG.GGGG.GG..',
    '....GG.G.GG..G..',
    '.....G.G.GG.....',
    '.......G..G.....',
    '................',
  ],
]
export const GHOST_PAL: Palette = { G: '#dfe4f2', K: '#1a1a2a' }

// ------------------------------------------------------- small creatures ---
export const SMALL_FRAMES: Record<string, PixelMap[]> = {
  crab: [
    [
      '..KK........KK..',
      '.KK..........KK.',
      '.KK..........KK.',
      '..K...RRRR...K..',
      '..RRRRRRRRRRRR..',
      '.RRRRRRRRRRRRRR.',
      'RRRRWWRRRRWWRRRR',
      'RRRRWKRRRRWKRRRR',
      'RRRRRRRRRRRRRRRR',
      '.RRRRRRRRRRRRRR.',
      '..RRRRRRRRRRRR..',
      '...R..R..R..R...',
      '..R...R..R...R..',
      '.R....R..R....R.',
      '................',
      '................',
    ],
    [
      '................',
      '.KK..........KK.',
      '..KK........KK..',
      '..K...RRRR...K..',
      '..RRRRRRRRRRRR..',
      '.RRRRRRRRRRRRRR.',
      'RRRRWWRRRRWWRRRR',
      'RRRRWKRRRRWKRRRR',
      'RRRRRRRRRRRRRRRR',
      '.RRRRRRRRRRRRRR.',
      '..RRRRRRRRRRRR..',
      '..R...R..R...R..',
      '...R..R..R..R...',
      '....R.R..R.R....',
      '................',
      '................',
    ],
  ],
  gull: [
    [
      '.WW.............',
      'WWWW............',
      'WWWWW...........',
      '.WWWWWWW....WW..',
      '..WWWWWWWWWWWW..',
      '...WWWWWWWWWW...',
      '....WWWWWWWW....',
      '.....YYWWWW.....',
      '......Y.........',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '................',
      '.WW.............',
      'WWWW........WW..',
      'WWWWWWWW..WWWW..',
      '.WWWWWWWWWWWW...',
      '..WWWWWWWWWW....',
      '...YYWWWWWW.....',
      '....Y...........',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  bee: [
    [
      '....WW..WW......',
      '...WWWWWWWW.....',
      '...WWWWWWWW.....',
      '....KKYYKK......',
      '...KKYYKKYY.....',
      '...KKYYKKYY.....',
      '....KYYKKY......',
      '.....KKKK.......',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '....WW..WW......',
      '...WWWWWWWW.....',
      '....KKYYKK......',
      '...KKYYKKYY.....',
      '...KKYYKKYY.....',
      '....KYYKKY......',
      '.....KKKK.......',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  rat: [
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '..........KK....',
      '.........KKKK...',
      '....KKKKKKKKK...',
      '...KKKKKKKKKKK..',
      'T..KKKKKKKKWK...',
      'TT.KKKKKKKKKK...',
      '.TTKKKKKKKKK....',
      '..TKKKKKKKKK....',
      '...KK..KK.......',
      '...K....K.......',
      '................',
    ],
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '..........KK....',
      '.........KKKK...',
      '....KKKKKKKKK...',
      '...KKKKKKKKKKK..',
      '.T.KKKKKKKKWK...',
      'TT.KKKKKKKKKK...',
      'T.TKKKKKKKKK....',
      '..TKKKKKKKKK....',
      '....KK..KK......',
      '....K....K......',
      '................',
    ],
  ],
  bat: [
    [
      'K..............K',
      'KK............KK',
      'KKK..........KKK',
      'KKKK.KKKKKK.KKKK',
      '.KKKKKKKKKKKKKK.',
      '..KKKRKKKKRKKK..',
      '...KKKKKKKKKK...',
      '....KKKKKKKK....',
      '.....K.KK.K.....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '................',
      '.....KKKKKK.....',
      'KKKKKKKKKKKKKKKK',
      '.KKKKRKKKKRKKKK.',
      '..KKKKKKKKKKKK..',
      '...KKKKKKKKKK...',
      '....K.KKKK.K....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  spider: [
    [
      '....K......K....',
      '.....K....K.....',
      '..K...K..K...K..',
      '...K..KKKK..K...',
      '....KKKKKKKK....',
      '....KKRKKRKK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
      '...K...KK...K...',
      '..K....KK....K..',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '...K........K...',
      '....K......K....',
      '.K....K..K....K.',
      '..K...KKKK...K..',
      '....KKKKKKKK....',
      '....KKRKKRKK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
      '....K..KK..K....',
      '...K...KK...K...',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  crow: [
    [
      '.KK.............',
      'KKKK............',
      'KKKKK...........',
      '.KKKKKKK....KK..',
      '..KKKKKKKKKKKK..',
      '...KKKKKKKKKK...',
      '....KKKKKKKK....',
      '.....YYKKKK.....',
      '......Y.........',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '................',
      '.KK.............',
      'KKKK........KK..',
      'KKKKKKKK..KKKK..',
      '.KKKKKKKKKKKK...',
      '..KKKKKKKKKK....',
      '...YYKKKKKK.....',
      '....Y...........',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
  book: [
    [
      'KK............KK',
      'KKKK........KKKK',
      'KKWWKK....KKWWKK',
      'KKWWWWKKKKWWWWKK',
      '.KKWWWWKKWWWWKK.',
      '..KKWWWWWWWWKK..',
      '...KKWWWWWWKK...',
      '....KKKKKKKK....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      'KKKK........KKKK',
      'KKWWKKKKKKKKWWKK',
      '.KKWWWWKKWWWWKK.',
      '..KKWWWWWWWWKK..',
      '...KKWWWWWWKK...',
      '....KKKKKKKK....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
}

export const SMALL_PALETTES: Record<string, Palette> = {
  crab: { R: '#d84a3a', K: '#7a2a20', W: '#f0e8d8' },
  gull: { W: '#eef2f6', Y: '#e8a83a', K: '#202030' },
  bee: { K: '#202018', Y: '#e8c83a', W: '#cfe4f0' },
  rat: { K: '#4a4048', W: '#e8e0d8', T: '#8a7a72' },
  bat: { K: '#2a2435', R: '#d84a3a' },
  spider: { K: '#28222e', R: '#c84a4a' },
  crow: { K: '#23232e', Y: '#caa83a' },
  book: { K: '#6a3a2a', W: '#e8e2d0' },
}
